Repository PSM-GeoTag-Project/GeoTag, pull requests merged in 2020-04, with the labels that each got.

#23 Uploading homepage
  GeoTag-Homepage1.html
  app.js
  images/krakow1.jpg
  images/krakow2.jpg
  images/krakow3.jpg
  images/krakow4.jpg
  images/logo.png
  images/logofinal.png
  styles.css
Labels: enhancement

#26 Adding login and register functionalty
  Firebase/firebase-debug.log
  Firebase/public/index.html
  Firebase/public/js/index.js
  Firebase/public/js/loginScripts.js
  Firebase/public/login.html
  Firebase/public/styles.css
  LICENSE
Labels: enhancement

#28 Fixed login subpages
  Firebase/firebase-debug.log
  Firebase/public/index.html
  Firebase/public/js/loginScripts.js
  Firebase/public/login.html
Labels: bug

#29 Fixed homepage
  Firebase/public/index.html
  Firebase/public/js/index.js
  Firebase/public/js/loginScripts.js
  Firebase/public/styles.css
Labels: bug

#31 Some work I made on the landmark template
  Firebase/public/images/kamieniolom_test.PNG
  Firebase/public/index.html
  Firebase/public/landmarks.html
  Firebase/public/styles.css
Labels: enhancement

#34 Little spring clean up
  GeoTag/.firebaserc
  GeoTag/firebase.json
  GeoTag/public/404.html
  GeoTag/public/images/kamieniolom_test.PNG
  GeoTag/public/images/krakow1.jpg
  GeoTag/public/images/krakow2.jpg
  GeoTag/public/images/krakow3.jpg
  GeoTag/public/images/krakow4.jpg
  GeoTag/public/images/logo.png
  GeoTag/public/images/logofinal.png
  GeoTag/public/index.html
  GeoTag/public/js/index.js
  GeoTag/public/js/loginScripts.js
  GeoTag/public/landmarks.html
  GeoTag/public/styles.css
Labels: enhancement

#37 Done template for landmark
  GeoTag/public/index.html
  GeoTag/public/js/map.js
  GeoTag/public/js/rating.js
  GeoTag/public/landmarks.html
  GeoTag/public/styles.css
  GeoTag/public/testmap.html
Labels: enhancement

#38 Added rank and log in button to homepage
  GeoTag/public/index.html
  GeoTag/public/js/rating.js
  GeoTag/public/landmarks.html
  GeoTag/public/styles.css
Labels: FEATURE

#39 Connection to db
  GeoTag/public/js/landmarks.js
  GeoTag/public/js/map.js
  GeoTag/public/landmarks.html
Labels: FEATURE

#47 Prototypeanduml
  GeoTag/Documentation GeoTag/Prototyp GeoTag.docx
  GeoTag/Documentation GeoTag/Use Case Diagram GeoTag.png
  GeoTag/public/landmarks.html
Labels: documentation

#48 Cloud Datastorage and URL links differentiate
  GeoTag/public/js/landmarks.js
  GeoTag/public/landmarks.html
Labels: enhancement

#49 Added random landmark button on homepage and implemented ranking
  GeoTag/public/index.html
  GeoTag/public/js/index.js
  GeoTag/public/js/landmarks.js
  GeoTag/public/js/rating.js
  GeoTag/public/landmarks.html
  GeoTag/public/styles.css
Labels: FEATURE

#50 Prepared content for whole website and filled out database
  GeoTag/Documentation GeoTag/2020-04-30T14_47_41_93961_all_namespaces_all_kinds_output-0 (1)
  GeoTag/public/js/landmarks.js
Labels: enhancement

#51 Filled db finished
  GeoTag/Documentation GeoTag/2020-04-30T14_47_41_93961_all_namespaces_all_kinds_output-0 (1)
  GeoTag/Documentation GeoTag/database_content.txt
Labels: enhancement
