Repository PSM-GeoTag-Project/GeoTag, pull requests merged in 2020-05, with the labels that each got.

#53 Rating feature added and login verification. Also fixed login name.
  GeoTag/public/images/fav.png
  GeoTag/public/images/icon-192x192.png
  GeoTag/public/images/icon-512x512.png
  GeoTag/public/images/icon.psd
  GeoTag/public/index.html
  GeoTag/public/js/index.js
  GeoTag/public/js/landmarks.js
  GeoTag/public/js/rating.js
  GeoTag/public/landmarks.html
  GeoTag/public/manifest.webmanifest
  GeoTag/public/sw.js
  GeoTag/public/testmap.html
Labels: enhancement

#57 Fixed footer height
  GeoTag/public/landmarks.html
Labels: documentation

#58 Fixed footer height
  GeoTag/public/landmarks.html
Labels: documentation

#59 New homepage photos
  GeoTag/public/images/10.jpg
  GeoTag/public/images/11.JPG
  GeoTag/public/images/12.jpg
  GeoTag/public/images/13.jpeg
  GeoTag/public/images/14.JPG
  GeoTag/public/images/15.jpg
  GeoTag/public/images/16.jpg
  GeoTag/public/images/2.jpg
  GeoTag/public/images/3.jpg
  GeoTag/public/images/4.jpg
  GeoTag/public/images/5.jpg
  GeoTag/public/images/6.jpg
  GeoTag/public/images/7.jpg
  GeoTag/public/images/8.jpeg
  GeoTag/public/images/9.jpg
  GeoTag/public/images/kamieniolom_test.PNG
  GeoTag/public/images/krakow1.jpg
  GeoTag/public/images/krakow2.jpg
  GeoTag/public/images/krakow3.jpg
  GeoTag/public/images/krakow4.jpg
  GeoTag/public/index.html
Labels: enhancement

#61 Fixed front page width
  GeoTag/public/index.html
  GeoTag/public/js/index.js
  GeoTag/public/styles.css
Labels: bug

#62 Fixed front page width
  GeoTag/public/styles.css
Labels: bug
